# RUNME FIRST

In [ ]:
import numpy as np
from sympy import Matrix

# ITSU1012-05 Matrix Worked Example 01

Define matrices

In [ ]:
# A = [[2, 5],
#      [3, 6],
#      [4, 7]]

# define A as an matrix using numpy array
A = np.array([[2, 5],
                 [3, 6],
                 [4, 7]])

In [ ]:
# B = [[1, 2, 3],
#      [-1, -2, -3]]

# Define B using numpy array
B = np.array([[1, 2, 3],
              [-1, -2, -3]])

In [ ]:
# C = [[-1],
#      [-2],
#      [-3]]

# Define C using numpy array
C = np.array([[-1],
              [-2],
              [-3]])


D is not a matrix because the number of elements in each row is not the same<br>
D = [[1, 2, 3], [6 <blank> <blank>]]

Note the difference between C and C1

In [ ]:
# C1 = [[-1, -2, -3]]

# Define C1 using numpy array
C1 = np.array([[-1, -2, -3]])


Print the order of the matrices

In [ ]:
# print("The order of matrix A is", len(A), "x", len(A[0]))
# print("The order of matrix B is", len(B), "x", len(B[0]))
# print("The order of matrix C is", len(C), "x", len(C[0]))

# print the order of matrix A, B, C
print("The order of matrix A is", np.shape(A))
print("The order of matrix B is", np.shape(B))
print("The order of matrix C is", np.shape(C))

The order of matrix A is (2, 2)
The order of matrix B is (2, 2)
The order of matrix C is (3, 1)


Print the elements of the matrices at position (2, 1)<br>
Note that the index is 0-based (the index starts from 0)

In [ ]:
print("The element at position (2, 1) in matrix A is", A[1][0])
print("The element at position (2, 1) in matrix B is", B[1][0])
print("The element at position (2, 1) in matrix C is", C[1][0])

The element at position (2, 1) in matrix A is 4
The element at position (2, 1) in matrix B is -3
The element at position (2, 1) in matrix C is -2


Print the elements of the matrices at position (1, 3)<br>
Note that the index is 0-based (the index starts from 0)<br>
Should these lines work?<br>
print("The element at position (1, 3) in matrix A is", A[0][2])<br>
print("The element at position (1, 3) in matrix B is", B[0][2])<br>
print("The element at position (1, 3) in matrix C is", C[0][2])

# ITSU1012-05 Matrix Worked Example 02

Matrix addition

In [ ]:
# A = [[1, 2],
#      [3, 4]]

# Define A using numpy array
A = np.array([[1, 2],
                 [3, 4]])


In [ ]:
# B = [[1, 4],
#      [2, 3]]

# Define B using numpy array
B = np.array([[1, 4],
              [2, 3]])

In [ ]:
# C = [[2, 2, 0],
#      [2, 2, 0]]

# Define C using numpy array
C = np.array([[2, 2, 0],
              [2, 2, 0]])


print A and B

In [ ]:
print("Matrix A", A)



Matrix A [[1 2]
 [3 4]]


In [ ]:
print("Matrix B", B)

Matrix B [[1 4]
 [2 3]]


Matrix addition

In [ ]:
D = A + B
# Print the result
print("Matrix D")
print(D)


Matrix D
[[2 6]
 [5 7]]


Matrix subtraction<br>
Should this work?<br>
D = A - B

Should we use the following code?<br>
Should it work?<br>
D = B - C

# ITSU1012-05 Matrix Worked Example 03

Matrix multiplication by scalar

In [ ]:
# A = [[2, -3],
#     [4, 1]]

# Define A using numpy array
A = np.array([[2, -3],
              [4, 1]])

In [ ]:
# B = [[3, 3],
#      [-3, -2]]

# Define B using numpy array
B = np.array([[3, 3],
              [-3, -2]])

Print A and B

In [ ]:
print("Matrix A")
print(A)


Matrix A
[[ 2 -3]
 [ 4  1]]
Matrix B
[[1 4]
 [2 3]]


In [ ]:
print("Matrix B")
print(B)

Matrix B
[[1 4]
 [2 3]]


Multiply A by 2

In [ ]:
C = 2 * A
# Print the result
print("Matrix C")
print(C)


Matrix C
[[ 4 -6]
 [ 8  2]]


Multiply B by 5

In [ ]:
C = 5 * B
# Print the result
print("Matrix C")
print(C)

Matrix C
[[ 5 20]
 [10 15]]


Calculate 2*A + 5*B

In [ ]:
C = 2 * A + 5 * B
# Print the result
print("Matrix C")
print(C)

Matrix C
[[ 9 14]
 [18 17]]


Calculate 4*(A + B)

In [ ]:
C = 4 * (A + B)
# Print the result
print("Matrix C")
print(C)

Matrix C
[[12  4]
 [24 16]]


Calculate 2*(B - A)

In [ ]:
C = 2 * (B - A)
# Print the result
print("Matrix C")
print(C)


Matrix C
[[-2 14]
 [-4  4]]


# ITSU1012-05 Matrix Worked Example 03.1

Define matrices

In [ ]:
C = Matrix([[50, 35],
             [-15, 20]])

solve for A:  5*A = c

In [ ]:
A = C / 5
print("Matrix A")
print(A)

Matrix A
Matrix([[10, 7], [-3, 4]])


In [ ]:
# B = [[3, 2],
#      [1, 5]]
# C = [[6, 9],
#      [-2, 4]]

# Define B, C using numpy array
B = np.array([[3, 2],
                 [1, 5]])
C = np.array([[6, 9],
              [-2, 4]])

Solve for P: P + B = C

In [ ]:

P = C - B
print("Matrix P")
print(P)

Matrix P
[[ 3  7]
 [-3 -1]]


In [ ]:
# C = [[1, 2, -3],
#      [2, 0, 1]]
# D = [[3, 4, 7],
#      [-2, 6, -5]]

# Define C, D usin numpy array
C = np.array([[1, 2, -3],
              [2, 0, 1]])
D = np.array([[3, 4, 7],
              [-2, 6, -5]])

Solve for B: 2*B - C = D

In [ ]:
# B = (Matrix(D) + Matrix(C)) / 2

B = (D + C) / 2
print("Matrix B")
print(B)

Matrix B
[[4.  7.5]
 [1.5 5.5]]


# ITSU1012-05 Matrix Worked Example 04

Define the matrix using numpy

In [ ]:
points_matrix = np.array([[60, 63, 51],
                          [71, 64, 74],
                          [64, 69, 71],
                          [69, 72, 68]])

Calculate sum in every row (axis=1)

In [ ]:
row_sums = points_matrix.sum(axis=1)

Calculate sum in every column (axis=0)

In [ ]:
column_sums = points_matrix.sum(axis=0)

In [ ]:
print("Sum of each row:", row_sums)
print("Sum of each column:", column_sums)

Sum of each row: [174 209 204 209]
Sum of each column: [264 268 264]


# ITSU1012-05 Matrix Worked Example 05

Matrix multiplication

In [ ]:
A = Matrix([[1, 2, 3],
            [4, 5, 6]])
B = Matrix([[2, -1],
            [0, 4],
            [5, 3]])

Print A and B

In [ ]:
print("Matrix A")
print(A)
print("Matrix B")
print(B)

Matrix A
Matrix([[1, 2, 3], [4, 5, 6]])
Matrix B
Matrix([[2, -1], [0, 4], [5, 3]])


Print order of matrices

In [ ]:
print("The order of matrix A is", A.shape)
print("The order of matrix B is", B.shape)

The order of matrix A is (2, 3)
The order of matrix B is (3, 2)


Multiply A by B

In [ ]:
C = A * B
print("Matrix C")
print(C)

Matrix C
Matrix([[17, 16], [38, 34]])


Multiply B by A

In [ ]:
D = B * A
print("Matrix D")
print(D)

Matrix D
Matrix([[-2, -1, 0], [16, 20, 24], [17, 25, 33]])


# ITSU1012-05 Matrix Worked Example 06 (No ex 06)






# ITSU1012-05 Matrix Worked Example 07

In [ ]:
A = Matrix([[4, 1],
            [6, 3]])
B = Matrix([[3, -1],
            [-6, 4]])

Print A and B

In [ ]:
print("Matrix A")
print(A)
print("Matrix B")
print(B)

Matrix A
Matrix([[4, 1], [6, 3]])
Matrix B
Matrix([[3, -1], [-6, 4]])


Find A*B

In [ ]:
C = A * B
print("Matrix C")
print(C)

Matrix C
Matrix([[6, 0], [0, 6]])


Find the inverse of A

In [ ]:
A_inv = A.inv()
print("Matrix A_inv")
print(A_inv)

Matrix A_inv
Matrix([[1/2, -1/6], [-1, 2/3]])


# ITSU1012-05 Matrix Worked Example 07 (inverse of a 2x2 matrix)

Define a 2x2 matrix using sympy

Define symbols a, b, c, d with sympy

In [ ]:
from sympy import symbols
a, b, c, d = symbols('a b c d')

In [ ]:
A = Matrix([[a, b],
            [c, d]])

Find the inverse of A

In [ ]:
A_inv = A.inv()
print("Matrix A_inv")
print(A_inv)

Matrix A_inv
Matrix([[d/(a*d - b*c), -b/(a*d - b*c)], [-c/(a*d - b*c), a/(a*d - b*c)]])


# ITSU1012-05 Matrix Worked Example 08

Using sympy to declare matrix C

In [ ]:
C = Matrix([[2, -3],
            [1, 5]])

Find C^(-1)

In [ ]:
C_inv = C.inv()

In [ ]:
print("Matrix C_inv")

Matrix C_inv


# ITSU1012-05 Matrix Worked Example 09

In [ ]:
A = Matrix([[1, 2],
            [0, 3]])

In [ ]:
B = Matrix([[2, 5],
            [-2, 1]])

Solve for X: A*X = B

In [ ]:
X = A.inv() * B
print("Matrix X (AX = B): ", X)

Matrix X (AX = B):  Matrix([[10/3, 13/3], [-2/3, 1/3]])


Solve for X: X*A = B

In [ ]:
X = B * A.inv()
print("Matrix X (XA = B)", X)

Matrix X (XA = B) Matrix([[2, 1/3], [-2, 5/3]])


# ITSU1012-05 Matrix Worked Example 10

Solve <br>
3*x - y = 16<br>
2*x + 5*y = 5<br>
by matrix methods

In [ ]:
A = Matrix([[3, -1],
            [2, 5]])

In [ ]:
B = Matrix([[16],
            [5]])

Solve for X: A*X = B

In [ ]:
X = A.inv() * B

In [ ]:
print("Matrix X (AX = B)", X)

Matrix X (AX = B) Matrix([[5], [-1]])


*Section: TODO: Solving Matrix equations using MathGPTPro

* *italicized text*Section: Solving Matrix equations using Bing Chat

*Section: Solving Matrix equations using Wolfram Alpha

ITSU1012-05 Matrix Worked Example 11

Find the matrix which translate P(3, -2) to P1(-2, 1)

Translation matrix T (= P1 - P)

In [ ]:
T = Matrix([[-2 - 3],
            [1 - (-2)]])

In [ ]:
print("Matrix T:", T)

Matrix T: Matrix([[-5], [3]])


# End of ITSU1012  Matrix Worked Example 11

Reflection over x-axis

In [ ]:
Mox = Matrix([[1, 0],
                [0, -1]])

Reflection over y-axis

In [ ]:
Moy = Matrix([[-1, 0],
                [0, 1]])

Reflection over y = x

In [ ]:
Moyx = Matrix([[0, 1],
                [1, 0]])

Reflection over y = -x

In [ ]:
Moy_x = Matrix([[0, -1],
                [-1, 0]])

# ITSU1012-05 Matrix Worked Example 12

Find the image of the point P(-2, 5) under reflection in <br>
a) the x-axis <br>
b) the y-axis<br>
c) the line y = x

In [ ]:
P = Matrix([[-2],
            [5]])

Reflection over x-axis

In [ ]:
Mox = Matrix([[1, 0],
                [0, -1]])

In [ ]:
P1 = Mox * P
print("Matrix P1", P1)

Matrix P1 Matrix([[-2], [-5]])


Reflection over y-axis

In [ ]:
Moy = Matrix([[-1, 0],
                [0, 1]])

In [ ]:
P2 = Moy * P
print("Matrix P2", P2)

Reflection over y = x

In [ ]:
Moyx = Matrix([[0, 1],
                [1, 0]])

In [ ]:
P3 = Moyx * P
print("Matrix P3", P3)

Matrix P3 Matrix([[5], [-2]])


# ITSU1012-05 Matrix Worked Example 13

Rotation using matrix

Find the image of the point P(2, 5) under anti-clockwise rotation about of origin by <br>
a) 30 degrees<br>
b) 90 degrees

In [ ]:
P = Matrix([[2],
            [5]])

Rotation by 30 degrees

In [ ]:
theta = 30
R30 = Matrix([[np.cos(np.radians(theta)), -np.sin(np.radians(theta))],
              [np.sin(np.radians(theta)), np.cos(np.radians(theta))]])

In [ ]:
P1 = R30 * P
print("Matrix P1", P1)

Matrix P1 Matrix([[-0.767949192431122], [5.33012701892219]])


Rotation by 90 degrees

In [ ]:
theta = 90
R90 = Matrix([[np.cos(np.radians(theta)), -np.sin(np.radians(theta))],
              [np.sin(np.radians(theta)), np.cos(np.radians(theta))]])

In [ ]:
P2 = R90 * P
print("Matrix P2", P2)

Matrix P2 Matrix([[-5.00000000000000], [2.00000000000000]])


# ITSU1012-05 Matrix Bonus content  

In [ ]:
k = 2

The matrices for dilations by a factor of k in the X direction

In [ ]:
Dxk = Matrix([[k, 0],
                [0, 1]])

The matrices for dilations by a factor of k in the Y direction

In [ ]:
Dyk = Matrix([[1, 0],
                [0, k]])

The matrices for dilations by a factor of k about the origin

In [ ]:
Dk = Matrix([[k, 0],
                [0, k]])