# RUNME

In [ ]:
import numpy as np
import sympy as sp

# ITSU1012 - Lesson 05 Practical Examples

# ITSU1012 - Lesson 05 Practical Examples 01

In [ ]:
# A = [[2, -3, 5],
#      [6, 7, 1]]

# Define A using numpy array
A = np.array([[2, -3, 5],
              [6, 7, 1]])

In [ ]:
# B = [[8], [4], [2]]

# Define B using numpy array
B = np.array([[8],
              [4],
              [2]])

Print the order of A and B

In [ ]:
# print("The order of matrix A is", len(A), "x", len(A[0]))
# print("The order of matrix B is", len(B), "x", len(B[0]))

# print the order of A
print("The order of matrix A is", A.shape)
# print the order of B
print("The order of matrix B is", B.shape)

The order of matrix A is (2, 3)
The order of matrix B is (3, 1)


# ITSU1012 - Lesson 05 Practical Examples 02

In [ ]:
A = np.array([[-4, 10],
              [-6, 2]])

Find 2*A

In [ ]:
print("2*A is", 2*A)

2*A is [[ -8  20]
 [-12   4]]


Find -3*A

In [ ]:
print("-3*A is", -3*A)

-3*A is [[ 12 -30]
 [ 18  -6]]


Find -1/2*A

In [ ]:
print("-1/2*A is", -0.5*A)

-1/2*A is [[ 2. -5.]
 [ 3. -1.]]


Find 0.3*A

In [ ]:
print("0.3*A is", 0.3*A)

0.3*A is [[-1.2  3. ]
 [-1.8  0.6]]


# ITSU1012 - Lesson 05 Practical Examples 03

In [ ]:
# A = [[1, -2],
#      [3, 4]]

# Define A using numpy array
A = np.array([[1, -2],
              [3, 4]])

In [ ]:
# B = [[-5, -1],
#      [6, 3]]

# Define B using numpy array
B = np.array([[-5, -1],
              [6, 3]])

Find A+B

In [ ]:
print("A+B is", A + B)
# Find 2*A + B
print("2*A + B is", 2*A + B)
# Find A +2*B
print("A + 2*B is", A + 2*B)

A+B is [[-4 -3]
 [ 9  7]]
2*A + B is [[-3 -5]
 [12 11]]
A + 2*B is [[-9 -4]
 [15 10]]


# ITSU1012 - Lesson 05 Practical Examples 04

P = [[-2, 3], <br>
     [5, 4]]

Q = [[1, -4],<br>
    [-3, 2]]

In [ ]:
P = np.array([[-2, 3],
                [5, 4]])

In [ ]:
Q = np.array([[1, -4],
                [-3, 2]])

Find P - Q

In [ ]:
print("P - Q is", P - Q)
# Find 2*P - Q
print("2*P - Q is", 2*P - Q)
# Find P - 2*Q
print("P - 2*Q is", P - 2*Q)

P - Q is [[-3  7]
 [ 8  2]]
2*P - Q is [[-5 10]
 [13  6]]
P - 2*Q is [[-4 11]
 [11  0]]


# ITSU1012 - Lesson 05 Practical Examples 05

In [ ]:
A = sp.Matrix([[-9, 4],
               [8, -6]])

In [ ]:
a, b = sp.symbols('a b')
B = sp.Matrix([[a, b],
               [-10, 2]])

In [ ]:
c = sp.symbols('c')
C = sp.Matrix([[-6, -4],
                [-2, c]])

Solve for a, b, and c such that A + B = C

In [ ]:
solution = sp.solve(A + B - C)
print("The solution is", solution) # The solution is {a: 3, b: -8, c: -4}

The solution is {a: 3, b: -8, c: -4}


# ITSU1012 - Lesson 05 Practical Examples 06

In [ ]:
A = np.array([[3, 0],
              [0, 3]])

a = np.array([[-2], [4]])

Perform the matrix multiplication

In [ ]:
C = np.dot(A, a)

Print the result

In [ ]:
print("6.a: \n ", C)

6.a:  [[-6]
 [12]]


In [ ]:
A = np.array([[1, 0],
              [0, -1]])
a = np.array([[2], [3]])

Perform the matrix multiplication

In [ ]:
C = np.dot(A, a)

Print the result

In [ ]:
print("6.b: \n", C)

6.b: 
 [[ 2]
 [-3]]


In [ ]:
A = np.array([[0, 1],
              [1, 0]])

a = np.array([[3], [4]])

Perform the matrix multiplication

In [ ]:
C = np.dot(A, a)

Print the result

In [ ]:
print("6.c: \n", C)

6.c: 
 [[4]
 [3]]


# ITSU1012 - Lesson 05 Practical Examples 07

In [ ]:
A = np.array([[1, 0],
              [0, 1]])

In [ ]:
B = np.array([[-4, 2],
              [3, 5]])

Find A*B

In [ ]:
C = np.dot(A, B)
print("7.a: \n", C)

7.a:  [[-4  2]
 [ 3  5]]


Did you notice anything special about the matrix A?

In [ ]:
A = np.array([[3, 6],
                [-2, 4]])

In [ ]:
B = np.array([[1, 0],
                [0, 1]])

Find A*B

In [ ]:
C = np.dot(A, B)
print("7.b: \n", C)

7.b: 
 [[ 3  6]
 [-2  4]]


Did you notice anything special about the matrix B?

7.c Ask GPT <br>
What is the special name of the matrix

I = np.array([[1, 0],<br>
                [0, 1]])

# ITSU1012 - Lesson 05 Practical Examples 08



In [ ]:
A = np.array([[-3, 1],
                [2, 4]])

In [ ]:
B = np.array([[6, 4],
                [-7, 3]])

Find A*B

In [ ]:
C = np.dot(A, B)
print("8.a: A*B =  ", C)

Find B*A

In [ ]:
D = np.dot(B, A)
print("8.b: B*A = \n", D)

8.b: B*A =  [[-10  22]
 [ 27   5]]


Find A*B - B*A

In [ ]:
E = np.dot(A, B) - np.dot(B, A)
print("8.c: A*B - B*A = \n", E)

8.c: A*B - B*A = 
 [[-15 -31]
 [-43  15]]


# ITSU1012 - Lesson 05 Practical Examples 09

In [ ]:
P = np.array([[-5, 3],
              [4, -2]])

In [ ]:
Q = np.array([[2, 6],
             [-1, 3]])

In [ ]:
R = np.array([[-7, 3],
              [-2, 4]])

Work out P*Q

In [ ]:
PQ = np.dot(P, Q)
print("P*Q = \n", PQ)

P*Q = 
 [[-13 -21]
 [ 10  18]]


Work out Q*R

In [ ]:
QR = np.dot(Q, R)
print("Q*R = \n", QR)

Q*R = 
 [[-26  30]
 [  1   9]]


Workout (PQ)R

In [ ]:
PQ_R = np.dot(np.dot(P, Q), R)
print("(PQ)R = \n", PQ_R)

(PQ)R = 
 [[ 133 -123]
 [-106  102]]


Workout P(QR)

In [ ]:
P_QR = np.dot(P, np.dot(Q, R))
print("P(QR) = \n", P_QR)

P(QR) = 
 [[ 133 -123]
 [-106  102]]


In [ ]:
D = PQ_R - P_QR
print("D = \n", D)

D = 
 [[0 0]
 [0 0]]


The conclusion is that (PQ)R is (?) (or not?) equal to P(QR)<br>
Thus, matrix multiplication is associative (or not?)

# ITSU1012 - Lesson 05 Practical Examples 10

using SymPy to define a 2x2 matrix A = (a, 3), (b, -2) where a, b are symbols

In [ ]:
a, b = sp.symbols('a b')
A = sp.Matrix([[a, 3],
               [b, -2]])

In [ ]:
B = sp.Matrix([[1, 2],
               [3, 4]])
C = sp.Matrix([[-3, 1],
               [0, -5]])

In [ ]:
print("A = ", A)
print("B = ", B)
print("C = ", C)
print("A*B = ", A*B)
print("A*B - C = ", A*B - C)

A =  Matrix([[a, 3], [b, -2]])
B =  Matrix([[1, 2], [3, 4]])
C =  Matrix([[-3, 1], [0, -5]])
A*B =  Matrix([[a + 9, 2*a + 12], [b - 6, 2*b - 8]])
A*B - C =  Matrix([[a + 12, 2*a + 11], [b - 6, 2*b - 3]])


Solve for a and b such that A*B = C<br>
TODO: fix the error "The solution is []"

In [ ]:
solution = sp.solve(A*B - C, (a, b))

In [ ]:
print("The solution is", solution)

The solution is []


# ITSU1012 - Lesson 05 Practical Examples 11

In [ ]:
M = np.array([[-9, 3],
               [-12, 6]])

In [ ]:
print("M = ", M)
print("2M = ", 2*M)
print("(1/3)*M = ", (1/3)*M)
print("-2*M = ", -2*M)

M =  [[ -9   3]
 [-12   6]]
2M =  [[-18   6]
 [-24  12]]
(1/3)*M =  [[-3.  1.]
 [-4.  2.]]
-2*M =  [[ 18  -6]
 [ 24 -12]]


# ITSU1012 - Lesson 05 Practical Examples 12



In [ ]:
A = np.array([[8, -12],
              [-14, 10]])

In [ ]:
B = np.array([[-6, -1],
              [11, -13]])

Find A + B

In [ ]:
C = A + B
print("A + B = ", C)

A + B =  [[  2 -13]
 [ -3  -3]]


Find 2*A + B

In [ ]:
D = 2*A + B
print("2*A + B = ", D)

2*A + B =  [[ 10 -25]
 [-17   7]]


# ITSU1012 - Lesson 05 Practical Examples *13*

In [ ]:
P = np.array([[-5, -12],
              [9, 10]])

In [ ]:
Q = np.array([[-2, -8],
              [-1, 4]])

Find P - Q

In [ ]:
R = P - Q
print("P - Q = ", R)

P - Q =  [[-3 -4]
 [10  6]]


Find Q - P

In [ ]:
S = Q - P
print("Q - P = ", S)

Q - P =  [[  3   4]
 [-10  -6]]


Find (P-Q) - (Q-P)

In [ ]:
T = R - S
print("(P-Q) - (Q-P) = ", T)

(P-Q) - (Q-P) =  [[-6 -8]
 [20 12]]


Is T zero? <br>
TODO: What is the conclusion?

# ITSU1012 - Lesson 05 Practical Examples 14

In [ ]:
A = np.array([[-10, 3],
              [4, 5]])
a = np.array([[6], [-2]])

Perform the matrix multiplication

In [ ]:
C = np.dot(A, a)

Print the result

In [ ]:
print("14.a: ", C)

14.a:  [[-66]
 [ 14]]


In [ ]:
A = np.array([[-5, -7],
              [-3, -1]])

In [ ]:
a = np.array([[-4], [-3]])

Perform the matrix multiplication

In [ ]:
C = np.dot(A, a)

Print the result

In [ ]:
print("14.b: ", C)

14.b:  [[41]
 [15]]


In [ ]:
A = np.array([[-3, 0],
                 [0, 3]])
a = np.array([[3], [2]])

Perform the matrix multiplication

In [ ]:
C = np.dot(A, a)

Print the result

In [ ]:
print("14.c: ", C)

14.c:  [[-9]
 [ 6]]


# ITSU1012 - Lesson 05 Practical Examples 15

In [ ]:
A = np.array([[-1, -3],
              [2, -2]])

In [ ]:
B = np.array([[4, -2],
              [3, -5]])

Find A*B

In [ ]:
C = np.dot(A, B)
print("15.a: A*B = ", C)

15.a: A*B =  [[-13  17]
 [  2   6]]


Find B*A

In [ ]:
D = np.dot(B, A)
print("15.b: B*A = ", D)

15.b: B*A =  [[ -8  -8]
 [-13   1]]


Find A*B - B*A

In [ ]:
E = np.dot(A, B) - np.dot(B, A)

In [ ]:
print("15.c: A*B - B*A = ", E)

15.c: A*B - B*A =  [[-5 25]
 [15  5]]


TODO: Write the conclusion<br>
AB - BA is not equal to zero, thus matrix multiplication is not commutative

#  ITSU1012 - Lesson 05 Practical Examples 16



In [ ]:
a, b = sp.symbols('a b')
A = sp.Matrix([[a, -3],
                  [2, b]])

In [ ]:
B = sp.Matrix([[4, -1],
                  [-5, 3]])
C = sp.Matrix([[-1, -5],
                  [3, 1]])

In [ ]:
print("A = ", A)
print("B = ", B)
print("C = ", C)

A =  Matrix([[a, -3], [2, b]])
B =  Matrix([[4, -1], [-5, 3]])
C =  Matrix([[-1, -5], [3, 1]])


In [ ]:
print("A*B = ", A*B)
print("A*B - C = ", A*B - C)

A*B =  Matrix([[4*a + 15, -a - 9], [8 - 5*b, 3*b - 2]])
A*B - C =  Matrix([[4*a + 16, -a - 4], [5 - 5*b, 3*b - 3]])


Solve for a and b such that A*B = C

In [ ]:
solution = sp.solve(A*B - C, (a, b))

In [ ]:
print("The solution is", solution) # should be {a: -4, b: 1}

The solution is {a: -4, b: 1}


# ITSU1012 - Lesson 05 Practical Examples 17

In [ ]:
A = np.array([[2, 1],
              [5, 3]])

In [ ]:
B = np.array([[3, -1],
              [-5, 2]])

Find A*B

In [ ]:
C = np.dot(A, B)
print("17.a: A*B = ", C) # should be I

17.a: A*B =  [[1 0]
 [0 1]]


Find inverse of A

In [ ]:
A_inv = np.linalg.inv(A)
print("17.b: Inverse of A = ", A_inv)

17.b: Inverse of A =  [[ 3. -1.]
 [-5.  2.]]


# ITSU1012 - Lesson 05 Practical Examples 18

In [ ]:
A = np.array([[5, 3],
              [3, 2]])

In [ ]:
B = np.array([[-5, 7],
                 [-2, 3]])

In [ ]:
C = np.array([[5, 3],
                 [-6, -4]])

In [ ]:
D = np.array([[4, 2],
                 [10, 5]])

Find the determinant of A, B, C, and D

In [ ]:
det_A = np.linalg.det(A)
det_B = np.linalg.det(B)
det_C = np.linalg.det(C)
det_D = np.linalg.det(D) # Should be zero

In [ ]:
print("18.a: Determinant of A = ", det_A)
print("18.b: Determinant of B = ", det_B)
print("18.c: Determinant of C = ", det_C)
print("18.d: Determinant of D = ", det_D)

18.a: Determinant of A =  0.9999999999999987
18.b: Determinant of B =  -0.9999999999999987
18.c: Determinant of C =  -1.999999999999998
18.d: Determinant of D =  0.0


A square matrix whose determinant is zero is an example of a singular matrix.

# ITSU1012 - Lesson 05 Practical Examples 19:

In [ ]:
P = np.array([[-3, 1],
              [10, -4]])

Find det(P)

In [ ]:
det_P = np.linalg.det(P)
print("19: Determinant of P = ", det_P)

19: Determinant of P =  2.000000000000002


Find P^-1

In [ ]:
P_inv = np.linalg.inv(P)
print("Inverse of P = ", P_inv)

Inverse of P =  [[-2.  -0.5]
 [-5.  -1.5]]


# ITSU1012 - Lesson 05 Practical Examples 20



In [ ]:
A = np.array([[-3, 5],
              [1, -2]])

In [ ]:
B = np.array([[3, 6],
              [2, 5]])

In [ ]:
C = np.array([[3, 4],
              [8, 7]])

Find the inverse of A, B, and C

In [ ]:
A_inv = np.linalg.inv(A)
B_inv = np.linalg.inv(B)
C_inv = np.linalg.inv(C)

In [ ]:
print("20.a: Inverse of A = ", A_inv)
print("20.b: Inverse of B = ", B_inv)
print("20.c: Inverse of C = ", C_inv)

20.a: Inverse of A =  [[-2. -5.]
 [-1. -3.]]
20.b: Inverse of B =  [[ 1.66666667 -2.        ]
 [-0.66666667  1.        ]]
20.c: Inverse of C =  [[-0.63636364  0.36363636]
 [ 0.72727273 -0.27272727]]
